#!/bin/bash

function history_to_cmd {
declare command
remote="`who am i`"
path="`pwd`"
command=$(fc -ln -0)
if [ "$command" != "$old_command" ]; then
logger -p local2.notice -t "$USER : $remote" "DIR : $path CMD : $command"
fi
old_command=$command
}
trap history_to_cmd DEBUG
