#!/bin/bash

ec2id=`wget -q -O - http://169.254.169.254/latest/meta-data/instance-id`
yesterday=`date "+%Y%m%d" -d "-1days"`


mkdir /root/gdpr/${yesterday}
cp /var/log/cmd.log-${yesterday} /root/gdpr/${yesterday}/${ec2id}.log
aws s3 cp /root/gdpr/${yesterday}/${ec2id}.log s3://sggog-gdpr-logs/server/${yesterday}/
sleep 5
rm -rf /root/gdpr/${yesterday}
